---
title: "Stop making excuses: prioritize your sleep" 
---

Your day-to-day is stressful, time runs out and your commitment to get in bed on time vanishes. Tomorrow I will recover, you think. But you don't. At the beginning, it seems you are able to deal with everything, to keep your productivity up. The day stretches and sleep comes into a second place, until sleep deprivation becomes the main character. You can't focus, irritation is your mood and productivity sinks. You are just tired, very tired, and even after a full night's sleep, the recovery is not complete. There was actually no net gain: what you seemed to be gaining, you are losing it now, and foremost, there is a price to pay: your health. 

The symptoms you are undergoing through are only the tip of the iceberg: your brain is under stress, your immune system has weakened and you are more likely to suffer a heart attack. You decide to change your habits, so that the foggy mind is gone and your high productivity is back. For some weeks it works, through an active effort you manage to follow the plan and get the rest you need. Eventually, urgent responsabilities kick in: the project deadline, the exams, the kids... The cycle starts again, you go over the path that lead to the deterioration of you health. I will manage, you think, despite the exhaustion and the chaos. 

Your body is keeping score. Every sleep-deprived season leaves a scar. On the long-term, the chickens come home to roost. There will be a negative impact in your health. Please, do not understimate the power of rest. Sleep heals, and your body needs that healing.