project:
  type: website

website:
  title: "Clara Rivero Rodríguez"
  favicon: clara_logo.svg
  site-url: https://clara-rivero.github.io
  navbar:
    background: transparent
    collapse: false
    logo: clara_logo.svg
    left:
      - icon: linkedin
        href: 'https://www.linkedin.com/in/clarariverorodriguez/'
      - href: index.qmd
        text: Home
      - href: contact.qmd
        text: Contact

  sidebar:
    style: "docked"
    search: true 
    collapse-level: 2
    contents:
      - section: "Infographics"
        contents:
          - text: "Carpal tunnel syndrome"
            href: illustration/carpal-tunnel-syndrome.qmd
          - text: "CAR-T Therapy"
            href: illustration/car-t.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    sidebar: false
    page-layout: full #article
    # grid:
    #   sidebar-width: 300px
    include-in-header: google-verification.html

execute:
  freeze: auto