---
title: "Scientific illustration & healthcare communication"
---
Welcome to my website. I can help you with rigorous and appealing visuals and evidence-based content, so that your company's impact doesn't go unnoticed. 

&nbsp;

**Would you like to have a custom set of illustrations that truly represent your vision and technology?**    
Among AI-generated content and all the media noise, they make a huge difference. In any situation (internal or investor presentations, scientific posters, blog posts...), customized visuals convey a professional image and a polished communication strategy. Check out some sample projects:  
 - [Scientific illustration](illustration.qmd){.main-link}

&nbsp;

**Are you looking for flexible scientific support for your business?**    
I can help you reduce your workload by providing reliable research assistance, literature reviews and content creation adapted to the communication purpose: divulgation, promotion, internal documentation...I write about medicine here:  
 -  [Medical writing](medical-writing.qmd){.main-link}

&nbsp;

I’m a biomedical engineer currently pursuing a degree in medicine. I have worked in fast-paced environments and adapt quickly to different needs. Let's collaborate! [Contact](contact.qmd){.main-link}

